version: '3.3'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    hostname: postgres
    privileged: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - internal

  admin:
      image: adminer
      container_name: adminer
      restart: always
      depends_on: 
        - postgres
      ports:
        - 8081:8080
      networks:
      - internal
networks:
  internal:
